### ISSUE TITLE
Security: Cross-Site Scripting (XSS)

### ISSUE THREAD

**Issue by jlchereau** [Memba/Kidoju-Server#27]
# Cross-Site Scripting (XSS)
## Overview:
Cross-Site Scripting, also known as Content Injection, happens when a user is able to craft input to an application that is later returned back to users in an unsafe manner.

XSS allows an attacker to hijack the user's session, perform actions, and receive data on their behalf. If an attacker can control content of a page on the same domain, it effectively nullifies all client protection mechanisms, such as CSRF protection and SSL.

## Examples:

```
PUT /api/v1/users/me HTTP/1.1
Host: 127.0.0.1:3000


{"born":"11111111","description":"\";alert(1);","email":"ljon@andyet.net","firstName":"<script>alert('user.FirstName')</script>","lastName":"a<script>alert('user.LasttName')</script>","language":"","picture":"Http://www.google.com)"}

/* Response */
HTTP/1.1 200 OK
Access-Control-Allow-Origin: http://localhost:8000
Vary: Origin


{"picture":"Http://www.google.com)","lastName":"a<script>alert('user.LasttName')</script>","firstName":"<script>alert('user.FirstName')</script>","email":"ljon@andyet.net","born":"1970-01-01T03:05:11.111Z","description":"\";alert(1);","language":"","twitter":{"email":"jon_lamendola@twitter.com","firstName":"Jon","lastName":"Lamendola","id":"14161519","link":"http://www.twitter.com/jon_lamendola","locale":"en","picture":"https://pbs.twimg.com/profile_images/425795441137942528/MKPIEfkm_normal.jpeg","timezone":-28800},"updated":"2015-02-09T23:26:27.316Z","metrics":{"summaries":{"count":1},"comments":{"count":1}},"created":"2015-02-07T12:00:09.000Z","id":""}

```

Causes execution here.
![68747470733a2f2f636c6475702e636f6d2f4a56577739325f4432362e706e67](https://cloud.githubusercontent.com/assets/2556751/6217151/d5f6afa2-b608-11e4-8cad-3e5d6996e92b.png)

Unfortunately, as the client side application is currently in what appears to be an unfinished state,  it is difficult to test for Cross-Site Scripting thoroughly. We did however locate some additional places where validation was not performed, and recommend a thorough review of all text inputs to locate any places where content may not be validated.

## Recommendations:

All user input should be output encoded at it's endpoint, using a consistent encoding method appropriate for the output context. All user controlled data,  even if you think it may be going to potentially harmless endpoints, should be output encoded using a consistent method across the application.

A good rule of thumb is: **_validate_** input where the context is unknown, **_encode_** output for the context that is known. It is always the responsibility of the developer creating the output logic to encode content properly, because the developer who wrote the input logic may not know for sure how it will be used.

For example, a username field may be rendered in multiple contexts throughout the application, so the best approach is to use client side validation for User Experience, use a minimal server side input validation, and focus your efforts on individual encoding for each instance where username is injected into the page.  I have included a code example in JavaScript at the end of this section to demonstrate this further.

Code example:

```javascript
//Don't do this:
user.name = sanitize.HTML(request.userInput.userName); //Typically, entity encode <>&

reply(
  '<html> <title> Hello ' + user.name + '</title></html>'
);

// Because of this:
reply(
  '<script>' +
  'var someAnalyticsService({' +
  '	userName: "' +
  user.name +
  '"' +
'})');

// Instead, use something like this:
user.name = request.userInput.userName;
reply(
  '<html> <title> Hello ' + encodeForContext('html', user.name) + '</title></html>'
);
reply(
  '<script>' +
  'var someAnalyticsService({' +
  '	userName: "' +
  encodeForContext('script', user.name) +
  '"' +
'})');
```

## References:

For a more in depth explanation of XSS Vulnerabilities, see:

* [OWASP XSS Overview](https://www.owasp.org/index.php/Cross-site_Scripting_%28XSS%29)
* [OWASP XSS Types Overview](https://www.owasp.org/index.php/Types_of_Cross-Site_Scripting)
* [Attacking well-secured Web-Applications by using innerHTML Mutations](http://www.cse.chalmers.se/~d02pulse/thesis/innerhtml.pdf)

**Comment by jlchereau** [comment]
I am not sure I understand:

```js
reply(
  '<script>' +
  'var someAnalyticsService({' +
  ' userName: "' +
  user.name +
  '"' +
'})');
```

This is not something we would do.

**Comment by jlamendo** [comment]
Jacques, as the client side application was not in scope for this engagement, I had to assume that the worst implementation possible was being made - direct content reflection. 

As most strings on the application pass through input validation to prevent injection of HTML meta-characters, I marked these fields down as an XSS vulnerability because they did not validate input using the same method. As you can see, the input was assumed safe when building the sample pages, and because it was actually not safe I was able to get javascript execution on those pages.

In a general sense, XSS does only occur when you are dealing with strings, but this is only the case when a boolean is ensured to be a boolean, a date ensured to be a date, etc. There are also some special edge cases with JSON attribute access that can lead to a DOM based XSS issue when dealing with numbers, but finding those problems, and answering your questions here thoroughly would require a review of the client side code.

I can say, however, that my general impression here is you have too many methods that are encoding/validating strings in different ways. The biggest thing is to determine what characters are unsafe for a given context, and encode those characters consistently using the same method each time output is rendered to that context. 

When you mix together different methods from different frameworks, you introduce a possible risk of output being encoded/validated in a way that is safe for rendering into the page at location x, but is not safe for rendering into the page at location y. 

Using a webworker sounds like a safe approach in theory, but once again I would need to see the implementation before I can say that with confidence. Additionally, you can take a look at [DOMPurify](https://github.com/cure53/DOMPurify) from Mario Heiderich and Gareth Heyes, which while it will slow down rendering, will also make XSS near impossible if it is used correctly.

**Comment by jlchereau** [comment]
I'll focus on the scope of the assignment for now, that is https://github.com/Memba/Kidoju-Server and more specifically:

- https://github.com/Memba/Kidoju-Server/blob/master/test/samples/dataCRUD.html
- https://github.com/Memba/Kidoju-Server/blob/master/test/samples/dataFiltering.html
- https://github.com/Memba/Kidoju-Server/blob/master/test/samples/security.html

You say: *"We did however locate some additional places where validation was not performed, and recommend a thorough review of all text inputs to locate any places where content may not be validated."*

I have not identified any XSS vulnerability in dataCRUD.html or dataFiltering.html which are failry representative of our application.

The only vulnerability I could identify was in security.html as explained above. It has been fixed has follows:

Code now includes an escape function. See https://github.com/Memba/Kidoju-Server/blob/master/test/samples/security.js#L17.

```js
function htmlEncode(value) {
    return ("" + value).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");
}
```

And debug information are displayed as follows. See https://github.com/Memba/Kidoju-Server/blob/master/test/samples/security.js#L101

```js
window.debug.log('I am ' + htmlEncode(me.firstName) + ' ' + htmlEncode(me.lastName) + '.');
```

**Comment by jlamendo** [comment]
Jaques, this looks great. 

Confirmed fix. In regards to the JS user functions, I have written a small proof of concept while working on another project that allows users to render HTML using javascript without compromising security. If you need users to have access to the DOM, this would be the optimal approach. JSfiddle available [here](http://jsfiddle.net/8gh4n4ws/4/) as well.

https://gist.github.com/jlamendo/7f8600fb807087f99a57
